name: Build, Test, and Create PR

on:
  push:
    branches:
      - feat-*  

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug Branch Name
        run: |
          echo "Head ref: ${{ github.head_ref }}"
          echo "Ref: ${{ github.ref }}"

      - name: Set Default Branch if Empty
        run: |
          if [ -z "${{ github.head_ref }}" ]; then
            echo "Branch name is empty. Setting default branch."
            echo "DEFAULT_BRANCH=dev" >> $GITHUB_ENV
          else
            echo "DEFAULT_BRANCH=${{ github.head_ref }}" >> $GITHUB_ENV
          fi

      - name: Set up Node.js (Latest LTS)
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        run: npm install

      - name: Run build
        run: npm run build

      - name: Run tests if available
        run: |
          if grep -q '"test":' package.json; then
            npm test
          else
            echo "No test script found. Skipping tests..."
          fi

      - name: Synchronize remote branch
        run: |
          git fetch origin
          git checkout ${{ env.DEFAULT_BRANCH }}
          git pull origin ${{ env.DEFAULT_BRANCH }} || echo "Branch is up-to-date or does not exist remotely."

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Automated build and test success"
          branch: ${{ env.DEFAULT_BRANCH }}
          title: "${{ env.DEFAULT_BRANCH }}"
          body: |
            ## **ğŸ“ƒ**Â ê´€ë ¨ ì´ìŠˆ
            Related Issue: #${{ env.ISSUE_NUMBER }}

            ## ğŸ“Â ì£¼ìš” ì‘ì—… ë‚´ìš©
            ex) ì„¤ëª… í˜¹ì€ ìŠ¤í¬ë¦°ìƒ·

            ## ğŸ“ºÂ ìº¡ì³ë³¸
            (ì„ íƒì‚¬í•­)

            ## ğŸ’¬Â ë¦¬ë·° ìš”êµ¬ì‚¬í•­
            ex) ì˜ë…¼í•  ì  ë° íŠ¹ë³„íˆ ìš”êµ¬í•  ë¶€ë¶„
          base: dev
