name: Build, Test, and Create PR

on:
  push:
    branches:
      - feat-*  

permissions:
  contents: write          
  pull-requests: write     
  issues: write            
  actions: write    

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract Issue Number
        id: extract_issue_number
        run: |
          echo "BRANCH_NAME=${GITHUB_REF##*/}" >> $GITHUB_ENV
          ISSUE_NUMBER=$(echo ${GITHUB_REF##*/} | grep -oE '[0-9]+')
          if [ -z "$ISSUE_NUMBER" ]; then
            echo "No issue number found in branch name. Defaulting to UNKNOWN."
            echo "ISSUE_NUMBER=UNKNOWN" >> $GITHUB_ENV
          else
            echo "ISSUE_NUMBER=$ISSUE_NUMBER" >> $GITHUB_ENV
          fi

      - name: Set up Node.js (Latest LTS)
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*' # ìµœì‹  LTS ë²„ì „ ì‚¬ìš©
          cache: 'npm' # npm ìºì‹œ í™œì„±í™”

      - name: Install dependencies
        run: npm install

      - name: Run build
        run: npm run build

      - name: Run tests if available
        run: |
          if grep -q '"test":' package.json; then
            echo "Test script found. Running tests..."
            npm test
          else
            echo "No test script found. Skipping tests..."
          fi

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Automated build and test success"
          title: "${{ github.head_ref }}"
          body: |
            ## **ğŸ“ƒ**Â ê´€ë ¨ ì´ìŠˆ
            Related Issue: #${{ env.ISSUE_NUMBER }}

            ## ğŸ“Â ì£¼ìš” ì‘ì—… ë‚´ìš©
            ex) ì„¤ëª… í˜¹ì€ ìŠ¤í¬ë¦°ìƒ·

            ## ğŸ“ºÂ ìº¡ì³ë³¸
            (ì„ íƒì‚¬í•­)

            ## ğŸ’¬Â ë¦¬ë·° ìš”êµ¬ì‚¬í•­
            ex) ì˜ë…¼í•  ì  ë° íŠ¹ë³„íˆ ìš”êµ¬í•  ë¶€ë¶„
          base: dev
